[2018-12-07 01:09:22,854] [ERROR] [xinxideMacBook-Pro.local][getdata.py - line:111] 获取activitys异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/allactivity.log'
[2018-12-07 01:09:22,855] [ERROR] [xinxideMacBook-Pro.local][getdata.py - line:146] 计算遍历覆盖率异常!float division by zero
[2018-12-07 01:09:22,909] [ERROR] [xinxideMacBook-Pro.local][getdata.py - line:45] 获取安装耗时数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/install_app.log'
[2018-12-07 01:09:22,910] [INFO] [xinxideMacBook-Pro.local][getdata.py - line:60] 获取冷启动数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/lanuch_app.log'
[2018-12-07 01:09:22,913] [ERROR] [xinxideMacBook-Pro.local][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: 'images'
[2018-12-07 01:09:22,913] [ERROR] [xinxideMacBook-Pro.local][getdata.py - line:30] 获取登录数据异常![Errno 2] No such file or directory: '/Users/xinxi/PycharmProjects/maxauto/report/tmp/login_app.log'
[2018-12-07 01:10:53,531] [ERROR] [xinxideMacBook-Pro.local][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: 'images'
[2018-12-07 01:12:45,899] [INFO] [xinxideMacBook-Pro.local][server.py - line:32] 启动服务...
[2018-12-07 01:13:04,613] [INFO] [xinxideMacBook-Pro.local][server.py - line:32] 启动服务...
[2018-12-07 01:13:04,629] [INFO] [xinxideMacBook-Pro.local][_internal.py - line:88]  * Running on http://127.0.0.1:3031/ (Press CTRL+C to quit)
[2018-12-07 01:13:04,630] [INFO] [xinxideMacBook-Pro.local][_internal.py - line:88]  * Restarting with stat
[2018-12-07 01:13:04,854] [INFO] [xinxideMacBook-Pro.local][server.py - line:32] 启动服务...
[2018-12-07 01:13:04,860] [WARNING] [xinxideMacBook-Pro.local][_internal.py - line:88]  * Debugger is active!
[2018-12-07 01:13:04,879] [INFO] [xinxideMacBook-Pro.local][_internal.py - line:88]  * Debugger PIN: 120-762-539
[2018-12-07 01:13:36,217] [INFO] [xinxideMacBook-Pro.local][client.py - line:31] 开始获取报告!
[2018-12-07 01:13:36,322] [ERROR] [xinxideMacBook-Pro.local][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: 'images'
[2018-12-07 01:13:36,342] [INFO] [xinxideMacBook-Pro.local][_internal.py - line:88] 127.0.0.1 - - [07/Dec/2018 01:13:36] "POST /getreport HTTP/1.1" 200 -
[2018-12-07 01:13:36,343] [INFO] [xinxideMacBook-Pro.local][client.py - line:36] 服务端状态码:200
[2018-12-07 01:13:36,344] [INFO] [xinxideMacBook-Pro.local][client.py - line:40] 报告路径:/Users/xinxi/PycharmProjects/maxauto/report/reports/report_20181207011336.html
[2018-12-07 01:14:29,526] [INFO] [xinxideMacBook-Pro.local][client.py - line:31] 开始获取报告!
[2018-12-07 01:14:29,638] [ERROR] [xinxideMacBook-Pro.local][getdata.py - line:226] 获取崩溃图片异常![Errno 2] No such file or directory: 'images'
[2018-12-07 01:14:29,640] [INFO] [xinxideMacBook-Pro.local][_internal.py - line:88] 127.0.0.1 - - [07/Dec/2018 01:14:29] "POST /getreport HTTP/1.1" 200 -
[2018-12-07 01:14:29,641] [INFO] [xinxideMacBook-Pro.local][client.py - line:36] 服务端状态码:200
[2018-12-07 01:14:29,641] [INFO] [xinxideMacBook-Pro.local][client.py - line:40] 报告路径:/Users/xinxi/PycharmProjects/maxauto/report/reports/report_20181207011429.html
[2018-12-07 01:14:30,068] [INFO] [xinxideMacBook-Pro.local][_internal.py - line:88]  * Detected change in '/Users/xinxi/PycharmProjects/maxauto/config.py', reloading
[2018-12-07 01:14:30,111] [INFO] [xinxideMacBook-Pro.local][_internal.py - line:88]  * Restarting with stat
[2018-12-07 01:14:30,535] [INFO] [xinxideMacBook-Pro.local][server.py - line:32] 启动服务...
[2018-12-07 01:14:30,551] [WARNING] [xinxideMacBook-Pro.local][_internal.py - line:88]  * Debugger is active!
[2018-12-07 01:14:30,570] [INFO] [xinxideMacBook-Pro.local][_internal.py - line:88]  * Debugger PIN: 120-762-539
[2018-12-07 01:14:50,552] [INFO] [xinxideMacBook-Pro.local][client.py - line:31] 开始获取报告!
[2018-12-07 01:14:50,715] [INFO] [xinxideMacBook-Pro.local][_internal.py - line:88] 127.0.0.1 - - [07/Dec/2018 01:14:50] "POST /getreport HTTP/1.1" 200 -
[2018-12-07 01:14:50,721] [INFO] [xinxideMacBook-Pro.local][client.py - line:36] 服务端状态码:200
[2018-12-07 01:14:50,722] [INFO] [xinxideMacBook-Pro.local][client.py - line:40] 报告路径:/Users/xinxi/PycharmProjects/maxauto/report/reports/report_20181207011450.html
